name: Poll GitHub repos and generate TIL posts

on:
  schedule:
    - cron: '0 2 * * *'  # daily at 02:00 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run GitHub poller
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m til_blog.github_poller --config config.yml.template
      - name: Commit generated posts
        run: |
          git config user.name "til-bot"
          git config user.email "til-bot@users.noreply.github.com"
          git add site/content/posts
          git commit -m "chore: add daily TIL posts" || echo "no changes"
          git push
